site_name: ATLAS GRID SIMULATION
site_description: REDWOOD Collaboration
site_author: REDWOOD Collaboration
repo_name: ATLAS GRID SIMULATION
repo_url: https://github.com/REDWOOD24/ATLAS-GRID-SIMULATION


theme:
    name: material

nav:
    - Home: 'index.md'
    - 'Install Libraries & Tools': 'start/install.md'
    - ATLAS Grid:
        - PanDa:
            - 'Overview': 'components/kernel/overview/index.md'
            - 'REDWOOD': 'components/kernel/reference/index.md'
        - Technical Details: 'components/kernel/reference/index.md'
   
    - Simulation tools:
        - 'General Overview': 'fullsimlight/fullsimlight/index.md'
        - 'ATLAS specific Information': 'fullsimlight/fsl/index.md'
        - 'Other experiments': 'fullsimlight/gmclash/index.md'

    - 'Plugin Architecture':
        - 'Plugin Examples': 'fullsimlight/plugins/index.md'
        - 'Plugin Support': 'plugin_support.md'

    - Visualization:
        - 'How to use': 'fullsimlight/plugin-support/index.md'

    - For Developers:
        - 'Build the Libraries and Tools': 'dev/index.md'
        - 'Troubleshooting': 'dev/troubleshooting.md'
        - 'Contributing to the Documentation': 'dev/docs-contrib.md'
        - 'Dev FAQ': 'dev/dev-faq.md'
    - FAQ: 'faq.md'
    - Papers & Presentations: 'papers.md'
      #   - 'Public': 'papers/public.md'
      #  - 'Internal': 'papers/internal.md'
    - Team & History: 'about/team.md'
    - Contacts: 'about/contacts.md'

extra_css:
    - material_nested_lists_rendering.css

markdown_extensions:
    - smarty                # to use 'SmartyPants' typography extensions as '---' for em-dashes
    - admonition            # to use notes, warnings, tips, ...
    - footnotes             # to set footnotes
    - pymdownx.superfences  
    - pymdownx.superfences: # to use code blocks nested under lists items
        # make exceptions to highlighting of code:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
    - toc:
        permalink: true
    - markdown_include.include:
        base_path: docs
    - pymdownx.arithmatex:  # to use LaTeX syntax in Markdown files
        generic: true
    #- markdown.extensions.attr_list # to use custom css settings, e.g. {: .center}. Not used now

plugins:
  - search
  - macros:
        module_name: imgutils
        verbose: true # enables debug through the 'chatter' method
  - mermaid2 # for diagrams
  #- git-revision-date #TODO: the mkdocs docker image apparently lacks the git exec, so this cannot be used. Update the image!

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
